# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
class Meow < Formula
  desc "Deep clean and optimize your Mac"
  homepage "https://github.com/Niteeshkanungo/Meow"
  url "https://github.com/Niteeshkanungo/Meow/archive/refs/tags/V1.22.1.tar.gz"
  sha256 "" # Will be calculated automatically when you create the release
  license "MIT"
  head "https://github.com/Niteeshkanungo/Meow.git", branch: "main"

  depends_on "go" => :build

  def install
    # Build Go binaries first
    system "make", "build"
    
    # Install everything to libexec to preserve directory structure
    # This ensures scripts can find lib/ relative to themselves
    libexec.install Dir["*"]
    
    # Create symlinks in bin/ that point to libexec executables
    # The scripts use SCRIPT_DIR which will resolve to libexec, allowing them to find lib/
    bin.install_symlink libexec/"cat" => "meow"
    bin.install_symlink libexec/"meow"
    
    # Install bin scripts as symlinks so they can find lib/ in libexec
    Dir[libexec/"bin/*"].each do |script|
      next if File.directory?(script)
      bin.install_symlink script => File.basename(script)
    end
  end

  test do
    system "#{bin}/meow", "--version"
  end
end
